name: stitches_flutter_app
description: Stitches的Flutter App工程，支持更多的平台，比如Web、MacOs、Windows等.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 本地依赖
  presentation:
    path: ../stitches_flutter_packages/presentation
  framework:
    path: ../stitches_flutter_packages/framework
  data:
    path: ../stitches_flutter_packages/data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

