name: stitches_flutter_module
description: A new flutter module project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  ## 本地依赖
  presentation:
    path: ../stitches_flutter_packages/presentation
  framework:
    path: ../stitches_flutter_packages/framework
  framework_integrated:
    path: ../stitches_flutter_packages/framework_integrated
  data:
    path: ../stitches_flutter_packages/data

  ## 外部库依赖
  flutter:
    sdk: flutter
  
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: io.github.zxjzerg.stitches.flutter.module
    iosBundleIdentifier: io.github.zxjzerg.stitches.flutter.module
