name: framework
description: 提供基础能力，例如数据存储等
publish_to: none

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  ## 本地依赖
  core:
    path: ../core

  ## 外部库依赖
  # 本地存储的数据库
  localstore: ^1.2.3
  # 依赖注入
  get_it: ^7.2.0