name: presentation
description: presentation layer of stitches
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  # 本地依赖
  data:
    path: ../data
  core:
    path: ../core

  # 外部依赖
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  flutter_hooks: ^0.18.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
